One Hot Encoding


In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Sample categorical data
data = np.array([['Red'], ['Green'], ['Blue'], ['Red'], ['Blue']])

# Initialize the OneHotEncoder
encoder = OneHotEncoder(sparse_output=False) # sparse_output=False returns an array

# Fit and transform the data
encoded_data = encoder.fit_transform(data)

In [ ]:
encoded_data

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

Bag of words (BOW)






In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                           "dswithbappy watch dswithbappy",
                           "people write comment",
                           "dswithbappy write comment"], "output":[1,1,0,0]})

df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [ ]:
bow = cv.fit_transform(df["text"])

In [ ]:
bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 11 stored elements and shape (4, 5)>

In [ ]:
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [ ]:
#vocavulary
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'dswithbappy': 1, 'write': 4, 'comment': 0}


N-Grams

In [ ]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                           "dswithbappy watch dswithbappy",
                           "people write comment",
                           "dswithbappy write comment"], "output":[1,1,0,0]})

df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [ ]:
#BI-gram
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [ ]:
bow = cv.fit_transform(df["text"])

In [ ]:
bow.toarray()

array([[0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 1]])

In [ ]:
#vocavulary
print(cv.vocabulary_)

{'people watch': 2, 'watch dswithbappy': 4, 'dswithbappy watch': 0, 'people write': 3, 'write comment': 5, 'dswithbappy write': 1}


In [ ]:
#TI-gram
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [ ]:
bow = cv.fit_transform(df["text"])

In [ ]:
bow.toarray()

array([[0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0]])

In [ ]:
#vocavulary
print(cv.vocabulary_)

{'people watch dswithbappy': 2, 'dswithbappy watch dswithbappy': 0, 'people write comment': 3, 'dswithbappy write comment': 1}


TF-IDF(Term frequency inverse document frequency)

In [ ]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                           "dswithbappy watch dswithbappy",
                           "people write comment",
                           "dswithbappy write comment"], "output":[1,1,0,0]})

df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

In [ ]:
arr = tfidf.fit_transform(df["text"]).toarray()

In [ ]:
arr

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

Word2Vec

In [5]:
!unzip "/content/DATA/archive (2).zip" -d "/content/DATA/"

Archive:  /content/DATA/archive (2).zip
  inflating: /content/DATA/1 - A Game of Thrones.txt  
  inflating: /content/DATA/2 - A Clash of Kings.txt  
  inflating: /content/DATA/3 - A Storm of Swords.txt  
  inflating: /content/DATA/4 - A Feast for Crows.txt  
  inflating: /content/DATA/5 - A Dance with Dragons.txt  


In [6]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 57.3 MB/s eta 0:00:00


In [7]:
import numpy as np
import pandas as pd
import gensim
import os

In [8]:
!pip install --upgrade gensim --user

In [9]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [11]:
import os
story = []

for filename in os.listdir('DATA'):
    if filename.endswith('.txt'):
        with open(os.path.join('DATA', filename), 'r', encoding='utf-8', errors='ignore') as f:
            corpus = f.read()
            raw_sent = sent_tokenize(corpus)
            for sent in raw_sent:
                story.append(simple_preprocess(sent))


In [12]:
story

[['game',
  'of',
  'thrones',
  'book',
  'one',
  'of',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'by',
  'george',
  'martin',
  'prologue',
  'we',
  'should',
  'start',
  'back',
  'gared',
  'urged',
  'as',
  'the',
  'woods',
  'began',
  'to',
  'grow',
  'dark',
  'around',
  'them'],
 ['the', 'wildlings', 'are', 'dead'],
 ['do', 'the', 'dead', 'frighten', 'you'],
 ['ser',
  'waymar',
  'royce',
  'asked',
  'with',
  'just',
  'the',
  'hint',
  'of',
  'smile'],
 ['gared', 'did', 'not', 'rise', 'to', 'the', 'bait'],
 ['he',
  'was',
  'an',
  'old',
  'man',
  'past',
  'fifty',
  'and',
  'he',
  'had',
  'seen',
  'the',
  'lordlings',
  'come',
  'and',
  'go'],
 ['dead', 'is', 'dead', 'he', 'said'],
 ['we', 'have', 'no', 'business', 'with', 'the', 'dead'],
 ['are', 'they', 'dead'],
 ['royce', 'asked', 'softly'],
 ['what', 'proof', 'have', 'we'],
 ['will', 'saw', 'them', 'gared', 'said'],
 ['if',
  'he',
  'says',
  'they',
  'are',
  'dead',
  'that',
  'proof',


In [13]:
len(story)

158874

In [14]:
story[0]

['game',
 'of',
 'thrones',
 'book',
 'one',
 'of',
 'song',
 'of',
 'ice',
 'and',
 'fire',
 'by',
 'george',
 'martin',
 'prologue',
 'we',
 'should',
 'start',
 'back',
 'gared',
 'urged',
 'as',
 'the',
 'woods',
 'began',
 'to',
 'grow',
 'dark',
 'around',
 'them']

In [15]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [16]:
model.build_vocab(story)

In [17]:

model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(6575763, 8625265)

In [18]:
vec = model.wv.get_normed_vectors()

In [19]:
vec

array([[ 0.11785476, -0.05755222,  0.12438091, ..., -0.09844977,
        -0.0051922 ,  0.11865292],
       [-0.01399426, -0.05235018,  0.07227631, ..., -0.04958678,
        -0.00532667,  0.03670425],
       [-0.01430749, -0.05568621, -0.02874415, ..., -0.04761591,
         0.14894924, -0.11344727],
       ...,
       [-0.13894238, -0.11585737,  0.0352949 , ..., -0.0561591 ,
         0.19725402, -0.1596775 ],
       [ 0.06927259, -0.14358763,  0.04379055, ..., -0.05695722,
         0.08819725, -0.01773134],
       [ 0.10592929, -0.02602885,  0.13684782, ...,  0.06642951,
         0.00973891, -0.19685432]], dtype=float32)

In [20]:
vec[0]

array([ 0.11785476, -0.05755222,  0.12438091,  0.04288885, -0.09518436,
       -0.03671307,  0.16542071,  0.14144169, -0.09467235, -0.135401  ,
        0.03410937,  0.05374979, -0.0520425 , -0.04885588, -0.15154612,
        0.04346176,  0.03763168,  0.11129324, -0.07446363, -0.07461064,
        0.2705207 ,  0.10156475,  0.1117246 ,  0.08994666,  0.11426571,
       -0.06984459, -0.05148158,  0.06919344, -0.06090248,  0.15335833,
       -0.21508427, -0.07265974,  0.0265681 , -0.06584986, -0.01715531,
       -0.04273078,  0.102539  , -0.06890238,  0.0401029 , -0.03690406,
       -0.21830922,  0.12339411, -0.14543813, -0.05665467, -0.07668341,
        0.00442038, -0.06984853,  0.01497005,  0.260752  ,  0.16010548,
       -0.0499532 ,  0.02088555, -0.04497301, -0.20577265,  0.06031177,
        0.01518672,  0.1036099 , -0.03400694, -0.05345226,  0.17824918,
       -0.076397  , -0.03965188, -0.15673958, -0.0500977 ,  0.02979028,
       -0.05189977,  0.04067628, -0.01573831,  0.0578867 ,  0.04

In [21]:
len(vec[0])

100

In [22]:
model.wv.most_similar('daenerys')

[('targaryen', 0.7971112728118896),
 ('stormborn', 0.7827069759368896),
 ('princess', 0.7441742420196533),
 ('queen', 0.7188718914985657),
 ('rhaegar', 0.7039774656295776),
 ('aegon', 0.7037500739097595),
 ('unburnt', 0.702069103717804),
 ('myrcella', 0.6911546587944031),
 ('margaery', 0.6882268190383911),
 ('elia', 0.6870462894439697)]

In [23]:
model.wv.similarity('arya','sansa')

np.float32(0.8576769)

In [24]:
y = model.wv.index_to_key

In [25]:
from sklearn.decomposition import PCA

In [26]:
pca = PCA(n_components=3)

In [27]:
x = pca.fit_transform(model.wv.get_normed_vectors())

In [28]:
x

array([[ 0.18870643, -0.6075153 ,  0.01903754],
       [ 0.21245345, -0.3487091 , -0.02328831],
       [-0.28528363, -0.5594394 , -0.25907198],
       ...,
       [-0.07840941, -0.17887053, -0.30927655],
       [ 0.19018477, -0.41724828,  0.09470418],
       [-0.39301208, -0.44876644, -0.11600363]], dtype=float32)

In [29]:
len(x[0])

3

In [30]:
import plotly.express as px
fig = px.scatter_3d(x[200:300],x = 0, y = 1, z = 2, color = y[200:300])
fig.show()